DROP TABLE IF EXISTS LISTA;
DROP TABLE IF EXISTS CADASTRO;
CREATE TABLE LISTA (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  PRODUTO STRING NOT NULL,
  VALOR MONEY NOT NULL
);

CREATE TABLE CADASTRO (
  ID INTEGER PRIMARY KEY AUTOINCREMENT,
  USUARIO STRING NOT NULL,
  SENHA MONEY NOT NULL
);